"""Phonetically diverse calibration and evaluation sentence prompts for VoiceNo! V0.

Provides balanced prompts for silent articulation calibration sessions,
strictly separating calibration prompts from held-out evaluation prompts.
"""

from typing import List, Tuple

# Calibration sentences (~5 to 45 minutes of articulatory material)
CALIBRATION_PROMPTS: List[str] = [
    "THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG",
    "PACK MY BOX WITH FIVE DOZEN LIQUOR JUGS",
    "HOW VEXINGLY QUICK DAFT ZEBRAS JUMP",
    "SPHERES OF GLOSSY BLACK GLASS ARE VERY SMOOTH",
    "BRIGHT SUNLIGHT ILLUMINATES THE OCEAN SURFACE",
    "SILENT SPEECH GIVES FREEDOM OF PRIVATE COMMUNICATION",
    "A GENTLE BREEZE DRIFTED THROUGH THE OPEN WINDOW",
    "CLEAR SPEECH REQUIRES PRECISE ARTICULATION OF THE LIPS",
    "HE WAS CONFIDENT THAT HIS VOICENESS WOULD BE HEARD",
    "KNOWLEDGE AND WISDOM GROW WITH EVERY EXPERIENCE",
    "THE MORNING DEW GLISTENED ON THE GRASS",
    "PLEASE SPEAK CLEARLY AND DISTINCTLY WITHOUT MAKING NOISE",
    "TECHNOLOGY ENABLES ACCESSIBILITY FOR EVERYONE EVERYWHERE",
    "SHE FOUND COMFORT IN THE QUIET OF THE LIBRARY",
    "EVERY DETAIL MATTERS WHEN WE EXAMINE COMPLEX SYSTEMS",
    "COLD WINTER NIGHTS BRING CRISP AIR AND SHINING STARS",
    "THE SCIENTIST CAREFULLY RECORDED HER OBSERVATIONS",
    "CONTINUOUS EFFORT UNLOCKS POTENTIAL OVER TIME",
    "MODERN ART OFTEN CHALLENGES CONVENTIONAL THINKING",
    "WATER FLOWS NATURALLY DOWN THE WINDING RIVERBED",
    "MUSIC AND RHYTHM TRANSCEND ALL LANGUAGE BARRIERS",
    "THE SUN SET GENTLY BEHIND THE DISTANT MOUNTAIN RIDGE",
    "REGULAR CALIBRATION ALLOWS ACCURATE PERSONALIZED ADAPTATION",
    "THE SOUND OF SILENCE IS SOMETIMES THE STRONGEST MESSAGE",
    "EXPERIMENTS PROVE WHETHER HYPOTHESES ARE TRUE",
]

# Held-out evaluation prompts (NEVER seen during calibration / training)
EVALUATION_PROMPTS: List[str] = [
    "SILENCE IS NOT THE ABSENCE OF COMMUNICATION",
    "ADVANCED NEURAL NETWORKS DECODE VISUAL SIGNALS",
    "THE OLD TOWER STOOD TALL AGAINST THE STORMY SKY",
    "NEW OPPORTUNITIES ARISE WHEN CREATIVE MINDS MEET",
    "PATIENCE AND DISCIPLINE YIELD EXCEPTIONAL RESULTS",
    "THE QUIET WORKSHOP WAS FILLED WITH VALUABLE TOOLS",
    "A SUDDEN RAIN SHOWER SURPRISED THE CITY WALKERS",
    "LIGHT REFLECTED BRIGHTLY FROM THE POLISHED MIRROR",
    "UNDERSTANDING REQUIRES ACTIVE LISTENING AND OPEN MINDS",
    "FUTURE INNOVATIONS TRANSFORM EVERYDAY CHALLENGES",
]


def get_calibration_prompts(num_prompts: int = 10) -> List[str]:
    """Returns a subset of calibration prompts."""
    return CALIBRATION_PROMPTS[:min(num_prompts, len(CALIBRATION_PROMPTS))]


def get_evaluation_prompts(num_prompts: int = 5) -> List[str]:
    """Returns held-out evaluation prompts."""
    return EVALUATION_PROMPTS[:min(num_prompts, len(EVALUATION_PROMPTS))]
